"""
Global Fallback Biller Catalog
Real-world billers for 40+ countries across all major regions.
Used when external APIs (Method FI, Salt Edge) return no results.
"""

FALLBACK_BILLERS = {
    # ─── AMERICAS ───
    "US": [
        {"payee_code": "BLR-US-001", "name": "AT&T", "category": "Telecom", "country": "US"},
        {"payee_code": "BLR-US-002", "name": "Verizon", "category": "Telecom", "country": "US"},
        {"payee_code": "BLR-US-003", "name": "T-Mobile", "category": "Telecom", "country": "US"},
        {"payee_code": "BLR-US-004", "name": "Comcast / Xfinity", "category": "Internet", "country": "US"},
        {"payee_code": "BLR-US-005", "name": "Spectrum (Charter)", "category": "Internet", "country": "US"},
        {"payee_code": "BLR-US-006", "name": "Cox Communications", "category": "Internet", "country": "US"},
        {"payee_code": "BLR-US-007", "name": "Google Fiber", "category": "Internet", "country": "US"},
        {"payee_code": "BLR-US-008", "name": "Duke Energy", "category": "Utilities", "country": "US"},
        {"payee_code": "BLR-US-009", "name": "Pacific Gas & Electric (PG&E)", "category": "Utilities", "country": "US"},
        {"payee_code": "BLR-US-010", "name": "Southern California Edison", "category": "Utilities", "country": "US"},
        {"payee_code": "BLR-US-011", "name": "Florida Power & Light", "category": "Utilities", "country": "US"},
        {"payee_code": "BLR-US-012", "name": "National Grid", "category": "Utilities", "country": "US"},
        {"payee_code": "BLR-US-013", "name": "Con Edison", "category": "Utilities", "country": "US"},
        {"payee_code": "BLR-US-014", "name": "American Water Works", "category": "Utilities", "country": "US"},
        {"payee_code": "BLR-US-015", "name": "Waste Management", "category": "Utilities", "country": "US"},
        {"payee_code": "BLR-US-016", "name": "State Farm Insurance", "category": "Insurance", "country": "US"},
        {"payee_code": "BLR-US-017", "name": "GEICO", "category": "Insurance", "country": "US"},
        {"payee_code": "BLR-US-018", "name": "Progressive Insurance", "category": "Insurance", "country": "US"},
        {"payee_code": "BLR-US-019", "name": "Allstate Insurance", "category": "Insurance", "country": "US"},
        {"payee_code": "BLR-US-020", "name": "Netflix", "category": "Subscription", "country": "US"},
        {"payee_code": "BLR-US-021", "name": "Spotify", "category": "Subscription", "country": "US"},
        {"payee_code": "BLR-US-022", "name": "Hulu", "category": "Subscription", "country": "US"},
        {"payee_code": "BLR-US-023", "name": "Disney+", "category": "Subscription", "country": "US"},
        {"payee_code": "BLR-US-024", "name": "ADT Security", "category": "Utilities", "country": "US"},
    ],
    "CA": [
        {"payee_code": "BLR-CA-001", "name": "Bell Canada", "category": "Telecom", "country": "CA"},
        {"payee_code": "BLR-CA-002", "name": "Rogers Communications", "category": "Telecom", "country": "CA"},
        {"payee_code": "BLR-CA-003", "name": "Telus", "category": "Telecom", "country": "CA"},
        {"payee_code": "BLR-CA-004", "name": "Fido", "category": "Telecom", "country": "CA"},
        {"payee_code": "BLR-CA-005", "name": "Hydro One", "category": "Utilities", "country": "CA"},
        {"payee_code": "BLR-CA-006", "name": "BC Hydro", "category": "Utilities", "country": "CA"},
        {"payee_code": "BLR-CA-007", "name": "Hydro-Quebec", "category": "Utilities", "country": "CA"},
        {"payee_code": "BLR-CA-008", "name": "Enbridge Gas", "category": "Utilities", "country": "CA"},
        {"payee_code": "BLR-CA-009", "name": "Shaw Communications", "category": "Internet", "country": "CA"},
        {"payee_code": "BLR-CA-010", "name": "Manulife Insurance", "category": "Insurance", "country": "CA"},
        {"payee_code": "BLR-CA-011", "name": "Sun Life Financial", "category": "Insurance", "country": "CA"},
    ],
    "MX": [
        {"payee_code": "BLR-MX-001", "name": "Telcel", "category": "Telecom", "country": "MX"},
        {"payee_code": "BLR-MX-002", "name": "Telmex", "category": "Telecom", "country": "MX"},
        {"payee_code": "BLR-MX-003", "name": "AT&T Mexico", "category": "Telecom", "country": "MX"},
        {"payee_code": "BLR-MX-004", "name": "CFE (Comision Federal de Electricidad)", "category": "Utilities", "country": "MX"},
        {"payee_code": "BLR-MX-005", "name": "Totalplay", "category": "Internet", "country": "MX"},
        {"payee_code": "BLR-MX-006", "name": "Izzi Telecom", "category": "Internet", "country": "MX"},
        {"payee_code": "BLR-MX-007", "name": "Naturgy Mexico", "category": "Utilities", "country": "MX"},
        {"payee_code": "BLR-MX-008", "name": "Sky Mexico", "category": "Subscription", "country": "MX"},
    ],
    "BR": [
        {"payee_code": "BLR-BR-001", "name": "Vivo (Telefonica)", "category": "Telecom", "country": "BR"},
        {"payee_code": "BLR-BR-002", "name": "Claro Brasil", "category": "Telecom", "country": "BR"},
        {"payee_code": "BLR-BR-003", "name": "TIM Brasil", "category": "Telecom", "country": "BR"},
        {"payee_code": "BLR-BR-004", "name": "Oi", "category": "Telecom", "country": "BR"},
        {"payee_code": "BLR-BR-005", "name": "CPFL Energia", "category": "Utilities", "country": "BR"},
        {"payee_code": "BLR-BR-006", "name": "Enel Brasil", "category": "Utilities", "country": "BR"},
        {"payee_code": "BLR-BR-007", "name": "Sabesp (Water)", "category": "Utilities", "country": "BR"},
        {"payee_code": "BLR-BR-008", "name": "NET Virtua", "category": "Internet", "country": "BR"},
    ],
    "AR": [
        {"payee_code": "BLR-AR-001", "name": "Movistar Argentina", "category": "Telecom", "country": "AR"},
        {"payee_code": "BLR-AR-002", "name": "Claro Argentina", "category": "Telecom", "country": "AR"},
        {"payee_code": "BLR-AR-003", "name": "Personal (Telecom)", "category": "Telecom", "country": "AR"},
        {"payee_code": "BLR-AR-004", "name": "Edenor", "category": "Utilities", "country": "AR"},
        {"payee_code": "BLR-AR-005", "name": "Edesur", "category": "Utilities", "country": "AR"},
        {"payee_code": "BLR-AR-006", "name": "Metrogas", "category": "Utilities", "country": "AR"},
        {"payee_code": "BLR-AR-007", "name": "Fibertel", "category": "Internet", "country": "AR"},
        {"payee_code": "BLR-AR-008", "name": "AySA (Water)", "category": "Utilities", "country": "AR"},
    ],
    "CO": [
        {"payee_code": "BLR-CO-001", "name": "Claro Colombia", "category": "Telecom", "country": "CO"},
        {"payee_code": "BLR-CO-002", "name": "Movistar Colombia", "category": "Telecom", "country": "CO"},
        {"payee_code": "BLR-CO-003", "name": "Tigo Colombia", "category": "Telecom", "country": "CO"},
        {"payee_code": "BLR-CO-004", "name": "EPM (Empresas Publicas de Medellin)", "category": "Utilities", "country": "CO"},
        {"payee_code": "BLR-CO-005", "name": "Codensa / Enel Colombia", "category": "Utilities", "country": "CO"},
        {"payee_code": "BLR-CO-006", "name": "ETB", "category": "Internet", "country": "CO"},
    ],

    # ─── EUROPE ───
    "GB": [
        {"payee_code": "BLR-GB-001", "name": "British Gas", "category": "Utilities", "country": "GB"},
        {"payee_code": "BLR-GB-002", "name": "EDF Energy", "category": "Utilities", "country": "GB"},
        {"payee_code": "BLR-GB-003", "name": "Octopus Energy", "category": "Utilities", "country": "GB"},
        {"payee_code": "BLR-GB-004", "name": "Scottish Power", "category": "Utilities", "country": "GB"},
        {"payee_code": "BLR-GB-005", "name": "E.ON UK", "category": "Utilities", "country": "GB"},
        {"payee_code": "BLR-GB-006", "name": "Thames Water", "category": "Utilities", "country": "GB"},
        {"payee_code": "BLR-GB-007", "name": "BT (British Telecom)", "category": "Telecom", "country": "GB"},
        {"payee_code": "BLR-GB-008", "name": "Vodafone UK", "category": "Telecom", "country": "GB"},
        {"payee_code": "BLR-GB-009", "name": "Three UK", "category": "Telecom", "country": "GB"},
        {"payee_code": "BLR-GB-010", "name": "EE", "category": "Telecom", "country": "GB"},
        {"payee_code": "BLR-GB-011", "name": "Sky UK", "category": "Internet", "country": "GB"},
        {"payee_code": "BLR-GB-012", "name": "Virgin Media", "category": "Internet", "country": "GB"},
        {"payee_code": "BLR-GB-013", "name": "Aviva Insurance", "category": "Insurance", "country": "GB"},
        {"payee_code": "BLR-GB-014", "name": "Direct Line Insurance", "category": "Insurance", "country": "GB"},
        {"payee_code": "BLR-GB-015", "name": "TV Licence (BBC)", "category": "Subscription", "country": "GB"},
        {"payee_code": "BLR-GB-016", "name": "Council Tax", "category": "Government", "country": "GB"},
    ],
    "DE": [
        {"payee_code": "BLR-DE-001", "name": "Deutsche Telekom", "category": "Telecom", "country": "DE"},
        {"payee_code": "BLR-DE-002", "name": "Vodafone Germany", "category": "Telecom", "country": "DE"},
        {"payee_code": "BLR-DE-003", "name": "O2 Germany", "category": "Telecom", "country": "DE"},
        {"payee_code": "BLR-DE-004", "name": "E.ON Germany", "category": "Utilities", "country": "DE"},
        {"payee_code": "BLR-DE-005", "name": "EnBW", "category": "Utilities", "country": "DE"},
        {"payee_code": "BLR-DE-006", "name": "RWE", "category": "Utilities", "country": "DE"},
        {"payee_code": "BLR-DE-007", "name": "Vattenfall Germany", "category": "Utilities", "country": "DE"},
        {"payee_code": "BLR-DE-008", "name": "1&1 Internet", "category": "Internet", "country": "DE"},
        {"payee_code": "BLR-DE-009", "name": "Allianz Insurance", "category": "Insurance", "country": "DE"},
        {"payee_code": "BLR-DE-010", "name": "GEZ / ARD ZDF (Broadcasting)", "category": "Subscription", "country": "DE"},
    ],
    "FR": [
        {"payee_code": "BLR-FR-001", "name": "Orange France", "category": "Telecom", "country": "FR"},
        {"payee_code": "BLR-FR-002", "name": "SFR", "category": "Telecom", "country": "FR"},
        {"payee_code": "BLR-FR-003", "name": "Bouygues Telecom", "category": "Telecom", "country": "FR"},
        {"payee_code": "BLR-FR-004", "name": "Free Mobile", "category": "Telecom", "country": "FR"},
        {"payee_code": "BLR-FR-005", "name": "EDF (Electricite de France)", "category": "Utilities", "country": "FR"},
        {"payee_code": "BLR-FR-006", "name": "Engie (Gas)", "category": "Utilities", "country": "FR"},
        {"payee_code": "BLR-FR-007", "name": "Veolia (Water)", "category": "Utilities", "country": "FR"},
        {"payee_code": "BLR-FR-008", "name": "Free (Internet)", "category": "Internet", "country": "FR"},
        {"payee_code": "BLR-FR-009", "name": "AXA Insurance", "category": "Insurance", "country": "FR"},
        {"payee_code": "BLR-FR-010", "name": "Canal+", "category": "Subscription", "country": "FR"},
    ],
    "IT": [
        {"payee_code": "BLR-IT-001", "name": "TIM (Telecom Italia)", "category": "Telecom", "country": "IT"},
        {"payee_code": "BLR-IT-002", "name": "Vodafone Italia", "category": "Telecom", "country": "IT"},
        {"payee_code": "BLR-IT-003", "name": "Wind Tre", "category": "Telecom", "country": "IT"},
        {"payee_code": "BLR-IT-004", "name": "Iliad Italia", "category": "Telecom", "country": "IT"},
        {"payee_code": "BLR-IT-005", "name": "Enel Energia", "category": "Utilities", "country": "IT"},
        {"payee_code": "BLR-IT-006", "name": "Eni Gas e Luce", "category": "Utilities", "country": "IT"},
        {"payee_code": "BLR-IT-007", "name": "Acea (Water/Electric)", "category": "Utilities", "country": "IT"},
        {"payee_code": "BLR-IT-008", "name": "Fastweb", "category": "Internet", "country": "IT"},
        {"payee_code": "BLR-IT-009", "name": "Generali Insurance", "category": "Insurance", "country": "IT"},
        {"payee_code": "BLR-IT-010", "name": "Sky Italia", "category": "Subscription", "country": "IT"},
    ],
    "ES": [
        {"payee_code": "BLR-ES-001", "name": "Movistar Spain", "category": "Telecom", "country": "ES"},
        {"payee_code": "BLR-ES-002", "name": "Vodafone Spain", "category": "Telecom", "country": "ES"},
        {"payee_code": "BLR-ES-003", "name": "Orange Spain", "category": "Telecom", "country": "ES"},
        {"payee_code": "BLR-ES-004", "name": "Iberdrola", "category": "Utilities", "country": "ES"},
        {"payee_code": "BLR-ES-005", "name": "Endesa", "category": "Utilities", "country": "ES"},
        {"payee_code": "BLR-ES-006", "name": "Naturgy", "category": "Utilities", "country": "ES"},
        {"payee_code": "BLR-ES-007", "name": "Mapfre Insurance", "category": "Insurance", "country": "ES"},
        {"payee_code": "BLR-ES-008", "name": "MasMovil", "category": "Internet", "country": "ES"},
    ],
    "NL": [
        {"payee_code": "BLR-NL-001", "name": "KPN", "category": "Telecom", "country": "NL"},
        {"payee_code": "BLR-NL-002", "name": "T-Mobile Netherlands", "category": "Telecom", "country": "NL"},
        {"payee_code": "BLR-NL-003", "name": "Vodafone Netherlands", "category": "Telecom", "country": "NL"},
        {"payee_code": "BLR-NL-004", "name": "Vattenfall Netherlands", "category": "Utilities", "country": "NL"},
        {"payee_code": "BLR-NL-005", "name": "Eneco", "category": "Utilities", "country": "NL"},
        {"payee_code": "BLR-NL-006", "name": "Essent", "category": "Utilities", "country": "NL"},
        {"payee_code": "BLR-NL-007", "name": "Ziggo", "category": "Internet", "country": "NL"},
        {"payee_code": "BLR-NL-008", "name": "Achmea Insurance", "category": "Insurance", "country": "NL"},
    ],
    "BE": [
        {"payee_code": "BLR-BE-001", "name": "Proximus", "category": "Telecom", "country": "BE"},
        {"payee_code": "BLR-BE-002", "name": "Orange Belgium", "category": "Telecom", "country": "BE"},
        {"payee_code": "BLR-BE-003", "name": "Telenet", "category": "Internet", "country": "BE"},
        {"payee_code": "BLR-BE-004", "name": "Engie Electrabel", "category": "Utilities", "country": "BE"},
        {"payee_code": "BLR-BE-005", "name": "Luminus", "category": "Utilities", "country": "BE"},
        {"payee_code": "BLR-BE-006", "name": "AG Insurance", "category": "Insurance", "country": "BE"},
    ],
    "CH": [
        {"payee_code": "BLR-CH-001", "name": "Swisscom", "category": "Telecom", "country": "CH"},
        {"payee_code": "BLR-CH-002", "name": "Sunrise", "category": "Telecom", "country": "CH"},
        {"payee_code": "BLR-CH-003", "name": "Salt Mobile", "category": "Telecom", "country": "CH"},
        {"payee_code": "BLR-CH-004", "name": "Axpo", "category": "Utilities", "country": "CH"},
        {"payee_code": "BLR-CH-005", "name": "Alpiq", "category": "Utilities", "country": "CH"},
        {"payee_code": "BLR-CH-006", "name": "Swiss Life Insurance", "category": "Insurance", "country": "CH"},
    ],
    "AT": [
        {"payee_code": "BLR-AT-001", "name": "A1 Telekom Austria", "category": "Telecom", "country": "AT"},
        {"payee_code": "BLR-AT-002", "name": "Magenta (T-Mobile Austria)", "category": "Telecom", "country": "AT"},
        {"payee_code": "BLR-AT-003", "name": "Drei (Three Austria)", "category": "Telecom", "country": "AT"},
        {"payee_code": "BLR-AT-004", "name": "Wien Energie", "category": "Utilities", "country": "AT"},
        {"payee_code": "BLR-AT-005", "name": "Verbund", "category": "Utilities", "country": "AT"},
        {"payee_code": "BLR-AT-006", "name": "Wiener Stadtwerke", "category": "Utilities", "country": "AT"},
    ],
    "SE": [
        {"payee_code": "BLR-SE-001", "name": "Telia Sweden", "category": "Telecom", "country": "SE"},
        {"payee_code": "BLR-SE-002", "name": "Tele2", "category": "Telecom", "country": "SE"},
        {"payee_code": "BLR-SE-003", "name": "Tre (Three Sweden)", "category": "Telecom", "country": "SE"},
        {"payee_code": "BLR-SE-004", "name": "Vattenfall", "category": "Utilities", "country": "SE"},
        {"payee_code": "BLR-SE-005", "name": "E.ON Sweden", "category": "Utilities", "country": "SE"},
        {"payee_code": "BLR-SE-006", "name": "Comhem", "category": "Internet", "country": "SE"},
    ],
    "NO": [
        {"payee_code": "BLR-NO-001", "name": "Telenor Norway", "category": "Telecom", "country": "NO"},
        {"payee_code": "BLR-NO-002", "name": "Telia Norway", "category": "Telecom", "country": "NO"},
        {"payee_code": "BLR-NO-003", "name": "Ice Norway", "category": "Telecom", "country": "NO"},
        {"payee_code": "BLR-NO-004", "name": "Hafslund", "category": "Utilities", "country": "NO"},
        {"payee_code": "BLR-NO-005", "name": "Fjordkraft", "category": "Utilities", "country": "NO"},
        {"payee_code": "BLR-NO-006", "name": "Altibox", "category": "Internet", "country": "NO"},
    ],
    "DK": [
        {"payee_code": "BLR-DK-001", "name": "TDC (Nuuday)", "category": "Telecom", "country": "DK"},
        {"payee_code": "BLR-DK-002", "name": "Telia Denmark", "category": "Telecom", "country": "DK"},
        {"payee_code": "BLR-DK-003", "name": "3 (Three Denmark)", "category": "Telecom", "country": "DK"},
        {"payee_code": "BLR-DK-004", "name": "Orsted", "category": "Utilities", "country": "DK"},
        {"payee_code": "BLR-DK-005", "name": "DONG Energy", "category": "Utilities", "country": "DK"},
        {"payee_code": "BLR-DK-006", "name": "Stofa", "category": "Internet", "country": "DK"},
    ],
    "FI": [
        {"payee_code": "BLR-FI-001", "name": "Elisa", "category": "Telecom", "country": "FI"},
        {"payee_code": "BLR-FI-002", "name": "DNA Finland", "category": "Telecom", "country": "FI"},
        {"payee_code": "BLR-FI-003", "name": "Telia Finland", "category": "Telecom", "country": "FI"},
        {"payee_code": "BLR-FI-004", "name": "Fortum", "category": "Utilities", "country": "FI"},
        {"payee_code": "BLR-FI-005", "name": "Helen (Helsinki Energy)", "category": "Utilities", "country": "FI"},
    ],
    "IE": [
        {"payee_code": "BLR-IE-001", "name": "Eir", "category": "Telecom", "country": "IE"},
        {"payee_code": "BLR-IE-002", "name": "Vodafone Ireland", "category": "Telecom", "country": "IE"},
        {"payee_code": "BLR-IE-003", "name": "Three Ireland", "category": "Telecom", "country": "IE"},
        {"payee_code": "BLR-IE-004", "name": "Electric Ireland", "category": "Utilities", "country": "IE"},
        {"payee_code": "BLR-IE-005", "name": "Bord Gais Energy", "category": "Utilities", "country": "IE"},
        {"payee_code": "BLR-IE-006", "name": "Irish Water", "category": "Utilities", "country": "IE"},
        {"payee_code": "BLR-IE-007", "name": "Sky Ireland", "category": "Internet", "country": "IE"},
    ],
    "PT": [
        {"payee_code": "BLR-PT-001", "name": "MEO (Portugal Telecom)", "category": "Telecom", "country": "PT"},
        {"payee_code": "BLR-PT-002", "name": "NOS", "category": "Telecom", "country": "PT"},
        {"payee_code": "BLR-PT-003", "name": "Vodafone Portugal", "category": "Telecom", "country": "PT"},
        {"payee_code": "BLR-PT-004", "name": "EDP (Energias de Portugal)", "category": "Utilities", "country": "PT"},
        {"payee_code": "BLR-PT-005", "name": "Galp Energia", "category": "Utilities", "country": "PT"},
    ],
    "PL": [
        {"payee_code": "BLR-PL-001", "name": "Orange Poland", "category": "Telecom", "country": "PL"},
        {"payee_code": "BLR-PL-002", "name": "Play (P4)", "category": "Telecom", "country": "PL"},
        {"payee_code": "BLR-PL-003", "name": "T-Mobile Poland", "category": "Telecom", "country": "PL"},
        {"payee_code": "BLR-PL-004", "name": "Plus (Polkomtel)", "category": "Telecom", "country": "PL"},
        {"payee_code": "BLR-PL-005", "name": "PGE (Polska Grupa Energetyczna)", "category": "Utilities", "country": "PL"},
        {"payee_code": "BLR-PL-006", "name": "Tauron", "category": "Utilities", "country": "PL"},
        {"payee_code": "BLR-PL-007", "name": "PGNiG (Gas)", "category": "Utilities", "country": "PL"},
        {"payee_code": "BLR-PL-008", "name": "UPC Poland", "category": "Internet", "country": "PL"},
    ],
    "GR": [
        {"payee_code": "BLR-GR-001", "name": "Cosmote", "category": "Telecom", "country": "GR"},
        {"payee_code": "BLR-GR-002", "name": "Vodafone Greece", "category": "Telecom", "country": "GR"},
        {"payee_code": "BLR-GR-003", "name": "Wind Hellas", "category": "Telecom", "country": "GR"},
        {"payee_code": "BLR-GR-004", "name": "DEI (Public Power Corp)", "category": "Utilities", "country": "GR"},
        {"payee_code": "BLR-GR-005", "name": "EYDAP (Water)", "category": "Utilities", "country": "GR"},
    ],

    # ─── ASIA ───
    "JP": [
        {"payee_code": "BLR-JP-001", "name": "NTT Docomo", "category": "Telecom", "country": "JP"},
        {"payee_code": "BLR-JP-002", "name": "SoftBank Mobile", "category": "Telecom", "country": "JP"},
        {"payee_code": "BLR-JP-003", "name": "au (KDDI)", "category": "Telecom", "country": "JP"},
        {"payee_code": "BLR-JP-004", "name": "Rakuten Mobile", "category": "Telecom", "country": "JP"},
        {"payee_code": "BLR-JP-005", "name": "TEPCO (Tokyo Electric)", "category": "Utilities", "country": "JP"},
        {"payee_code": "BLR-JP-006", "name": "Kansai Electric", "category": "Utilities", "country": "JP"},
        {"payee_code": "BLR-JP-007", "name": "Tokyo Gas", "category": "Utilities", "country": "JP"},
        {"payee_code": "BLR-JP-008", "name": "Osaka Gas", "category": "Utilities", "country": "JP"},
        {"payee_code": "BLR-JP-009", "name": "NTT Flets (Fiber)", "category": "Internet", "country": "JP"},
        {"payee_code": "BLR-JP-010", "name": "NHK (Broadcasting)", "category": "Subscription", "country": "JP"},
    ],
    "KR": [
        {"payee_code": "BLR-KR-001", "name": "SK Telecom", "category": "Telecom", "country": "KR"},
        {"payee_code": "BLR-KR-002", "name": "KT (Korea Telecom)", "category": "Telecom", "country": "KR"},
        {"payee_code": "BLR-KR-003", "name": "LG Uplus", "category": "Telecom", "country": "KR"},
        {"payee_code": "BLR-KR-004", "name": "KEPCO (Korea Electric)", "category": "Utilities", "country": "KR"},
        {"payee_code": "BLR-KR-005", "name": "Korea City Gas", "category": "Utilities", "country": "KR"},
        {"payee_code": "BLR-KR-006", "name": "SK Broadband", "category": "Internet", "country": "KR"},
        {"payee_code": "BLR-KR-007", "name": "Samsung Fire Insurance", "category": "Insurance", "country": "KR"},
    ],
    "CN": [
        {"payee_code": "BLR-CN-001", "name": "China Mobile", "category": "Telecom", "country": "CN"},
        {"payee_code": "BLR-CN-002", "name": "China Unicom", "category": "Telecom", "country": "CN"},
        {"payee_code": "BLR-CN-003", "name": "China Telecom", "category": "Telecom", "country": "CN"},
        {"payee_code": "BLR-CN-004", "name": "State Grid Corp", "category": "Utilities", "country": "CN"},
        {"payee_code": "BLR-CN-005", "name": "China Southern Power Grid", "category": "Utilities", "country": "CN"},
        {"payee_code": "BLR-CN-006", "name": "PetroChina (Gas)", "category": "Utilities", "country": "CN"},
        {"payee_code": "BLR-CN-007", "name": "China Life Insurance", "category": "Insurance", "country": "CN"},
        {"payee_code": "BLR-CN-008", "name": "Ping An Insurance", "category": "Insurance", "country": "CN"},
    ],
    "IN": [
        {"payee_code": "BLR-IN-001", "name": "Jio (Reliance)", "category": "Telecom", "country": "IN"},
        {"payee_code": "BLR-IN-002", "name": "Airtel India", "category": "Telecom", "country": "IN"},
        {"payee_code": "BLR-IN-003", "name": "Vi (Vodafone Idea)", "category": "Telecom", "country": "IN"},
        {"payee_code": "BLR-IN-004", "name": "BSNL", "category": "Telecom", "country": "IN"},
        {"payee_code": "BLR-IN-005", "name": "Tata Power", "category": "Utilities", "country": "IN"},
        {"payee_code": "BLR-IN-006", "name": "Adani Electricity", "category": "Utilities", "country": "IN"},
        {"payee_code": "BLR-IN-007", "name": "BESCOM (Bangalore Electric)", "category": "Utilities", "country": "IN"},
        {"payee_code": "BLR-IN-008", "name": "Mahanagar Gas", "category": "Utilities", "country": "IN"},
        {"payee_code": "BLR-IN-009", "name": "ACT Fibernet", "category": "Internet", "country": "IN"},
        {"payee_code": "BLR-IN-010", "name": "LIC (Life Insurance)", "category": "Insurance", "country": "IN"},
        {"payee_code": "BLR-IN-011", "name": "Tata Sky / Tata Play", "category": "Subscription", "country": "IN"},
    ],
    "SG": [
        {"payee_code": "BLR-SG-001", "name": "Singtel", "category": "Telecom", "country": "SG"},
        {"payee_code": "BLR-SG-002", "name": "StarHub", "category": "Telecom", "country": "SG"},
        {"payee_code": "BLR-SG-003", "name": "M1 Limited", "category": "Telecom", "country": "SG"},
        {"payee_code": "BLR-SG-004", "name": "SP Group (Utilities)", "category": "Utilities", "country": "SG"},
        {"payee_code": "BLR-SG-005", "name": "PUB (Water)", "category": "Utilities", "country": "SG"},
        {"payee_code": "BLR-SG-006", "name": "NTUC Income Insurance", "category": "Insurance", "country": "SG"},
        {"payee_code": "BLR-SG-007", "name": "ViewQwest", "category": "Internet", "country": "SG"},
    ],
    "HK": [
        {"payee_code": "BLR-HK-001", "name": "HKT (PCCW)", "category": "Telecom", "country": "HK"},
        {"payee_code": "BLR-HK-002", "name": "China Mobile Hong Kong", "category": "Telecom", "country": "HK"},
        {"payee_code": "BLR-HK-003", "name": "3 Hong Kong", "category": "Telecom", "country": "HK"},
        {"payee_code": "BLR-HK-004", "name": "CLP Power", "category": "Utilities", "country": "HK"},
        {"payee_code": "BLR-HK-005", "name": "HK Electric", "category": "Utilities", "country": "HK"},
        {"payee_code": "BLR-HK-006", "name": "Towngas", "category": "Utilities", "country": "HK"},
        {"payee_code": "BLR-HK-007", "name": "Water Supplies Department", "category": "Utilities", "country": "HK"},
    ],
    "MY": [
        {"payee_code": "BLR-MY-001", "name": "Maxis", "category": "Telecom", "country": "MY"},
        {"payee_code": "BLR-MY-002", "name": "Celcom", "category": "Telecom", "country": "MY"},
        {"payee_code": "BLR-MY-003", "name": "Digi", "category": "Telecom", "country": "MY"},
        {"payee_code": "BLR-MY-004", "name": "Tenaga Nasional (TNB)", "category": "Utilities", "country": "MY"},
        {"payee_code": "BLR-MY-005", "name": "Syabas (Water)", "category": "Utilities", "country": "MY"},
        {"payee_code": "BLR-MY-006", "name": "Unifi (TM)", "category": "Internet", "country": "MY"},
        {"payee_code": "BLR-MY-007", "name": "Astro", "category": "Subscription", "country": "MY"},
    ],
    "TH": [
        {"payee_code": "BLR-TH-001", "name": "AIS", "category": "Telecom", "country": "TH"},
        {"payee_code": "BLR-TH-002", "name": "TrueMove H", "category": "Telecom", "country": "TH"},
        {"payee_code": "BLR-TH-003", "name": "DTAC", "category": "Telecom", "country": "TH"},
        {"payee_code": "BLR-TH-004", "name": "PEA (Provincial Electricity)", "category": "Utilities", "country": "TH"},
        {"payee_code": "BLR-TH-005", "name": "MEA (Metropolitan Electricity)", "category": "Utilities", "country": "TH"},
        {"payee_code": "BLR-TH-006", "name": "True Online", "category": "Internet", "country": "TH"},
        {"payee_code": "BLR-TH-007", "name": "3BB Internet", "category": "Internet", "country": "TH"},
    ],
    "ID": [
        {"payee_code": "BLR-ID-001", "name": "Telkomsel", "category": "Telecom", "country": "ID"},
        {"payee_code": "BLR-ID-002", "name": "Indosat Ooredoo", "category": "Telecom", "country": "ID"},
        {"payee_code": "BLR-ID-003", "name": "XL Axiata", "category": "Telecom", "country": "ID"},
        {"payee_code": "BLR-ID-004", "name": "PLN (State Electricity)", "category": "Utilities", "country": "ID"},
        {"payee_code": "BLR-ID-005", "name": "PGN (Gas)", "category": "Utilities", "country": "ID"},
        {"payee_code": "BLR-ID-006", "name": "IndiHome (Telkom)", "category": "Internet", "country": "ID"},
        {"payee_code": "BLR-ID-007", "name": "PDAM (Water)", "category": "Utilities", "country": "ID"},
    ],
    "PH": [
        {"payee_code": "BLR-PH-001", "name": "Globe Telecom", "category": "Telecom", "country": "PH"},
        {"payee_code": "BLR-PH-002", "name": "Smart Communications", "category": "Telecom", "country": "PH"},
        {"payee_code": "BLR-PH-003", "name": "DITO Telecommunity", "category": "Telecom", "country": "PH"},
        {"payee_code": "BLR-PH-004", "name": "Meralco (Manila Electric)", "category": "Utilities", "country": "PH"},
        {"payee_code": "BLR-PH-005", "name": "Manila Water", "category": "Utilities", "country": "PH"},
        {"payee_code": "BLR-PH-006", "name": "Maynilad Water", "category": "Utilities", "country": "PH"},
        {"payee_code": "BLR-PH-007", "name": "PLDT Home Fibr", "category": "Internet", "country": "PH"},
        {"payee_code": "BLR-PH-008", "name": "Converge ICT", "category": "Internet", "country": "PH"},
    ],
    "VN": [
        {"payee_code": "BLR-VN-001", "name": "Viettel", "category": "Telecom", "country": "VN"},
        {"payee_code": "BLR-VN-002", "name": "Mobifone", "category": "Telecom", "country": "VN"},
        {"payee_code": "BLR-VN-003", "name": "Vinaphone", "category": "Telecom", "country": "VN"},
        {"payee_code": "BLR-VN-004", "name": "EVN (Electricity of Vietnam)", "category": "Utilities", "country": "VN"},
        {"payee_code": "BLR-VN-005", "name": "VNPT (Internet)", "category": "Internet", "country": "VN"},
        {"payee_code": "BLR-VN-006", "name": "FPT Telecom", "category": "Internet", "country": "VN"},
    ],
    "PK": [
        {"payee_code": "BLR-PK-001", "name": "Jazz (Mobilink)", "category": "Telecom", "country": "PK"},
        {"payee_code": "BLR-PK-002", "name": "Telenor Pakistan", "category": "Telecom", "country": "PK"},
        {"payee_code": "BLR-PK-003", "name": "Zong", "category": "Telecom", "country": "PK"},
        {"payee_code": "BLR-PK-004", "name": "Ufone", "category": "Telecom", "country": "PK"},
        {"payee_code": "BLR-PK-005", "name": "K-Electric", "category": "Utilities", "country": "PK"},
        {"payee_code": "BLR-PK-006", "name": "LESCO (Lahore Electric)", "category": "Utilities", "country": "PK"},
        {"payee_code": "BLR-PK-007", "name": "SSGC (Sui Southern Gas)", "category": "Utilities", "country": "PK"},
        {"payee_code": "BLR-PK-008", "name": "PTCL", "category": "Internet", "country": "PK"},
    ],
    "BD": [
        {"payee_code": "BLR-BD-001", "name": "Grameenphone", "category": "Telecom", "country": "BD"},
        {"payee_code": "BLR-BD-002", "name": "Robi Axiata", "category": "Telecom", "country": "BD"},
        {"payee_code": "BLR-BD-003", "name": "Banglalink", "category": "Telecom", "country": "BD"},
        {"payee_code": "BLR-BD-004", "name": "DESCO (Dhaka Electric)", "category": "Utilities", "country": "BD"},
        {"payee_code": "BLR-BD-005", "name": "DPDC (Dhaka Power)", "category": "Utilities", "country": "BD"},
        {"payee_code": "BLR-BD-006", "name": "Titas Gas", "category": "Utilities", "country": "BD"},
    ],
    "LK": [
        {"payee_code": "BLR-LK-001", "name": "Dialog Axiata", "category": "Telecom", "country": "LK"},
        {"payee_code": "BLR-LK-002", "name": "Mobitel", "category": "Telecom", "country": "LK"},
        {"payee_code": "BLR-LK-003", "name": "Hutch Lanka", "category": "Telecom", "country": "LK"},
        {"payee_code": "BLR-LK-004", "name": "CEB (Ceylon Electricity Board)", "category": "Utilities", "country": "LK"},
        {"payee_code": "BLR-LK-005", "name": "LECO (Lanka Electric)", "category": "Utilities", "country": "LK"},
        {"payee_code": "BLR-LK-006", "name": "Sri Lanka Telecom", "category": "Internet", "country": "LK"},
    ],

    # ─── MIDDLE EAST ───
    "AE": [
        {"payee_code": "BLR-AE-001", "name": "Etisalat (e&)", "category": "Telecom", "country": "AE"},
        {"payee_code": "BLR-AE-002", "name": "du", "category": "Telecom", "country": "AE"},
        {"payee_code": "BLR-AE-003", "name": "DEWA (Dubai Electricity & Water)", "category": "Utilities", "country": "AE"},
        {"payee_code": "BLR-AE-004", "name": "ADDC (Abu Dhabi Distribution)", "category": "Utilities", "country": "AE"},
        {"payee_code": "BLR-AE-005", "name": "SEWA (Sharjah Electricity & Water)", "category": "Utilities", "country": "AE"},
        {"payee_code": "BLR-AE-006", "name": "Salik (Road Toll)", "category": "Government", "country": "AE"},
        {"payee_code": "BLR-AE-007", "name": "ADNOC Gas", "category": "Utilities", "country": "AE"},
    ],
    "SA": [
        {"payee_code": "BLR-SA-001", "name": "STC (Saudi Telecom)", "category": "Telecom", "country": "SA"},
        {"payee_code": "BLR-SA-002", "name": "Mobily", "category": "Telecom", "country": "SA"},
        {"payee_code": "BLR-SA-003", "name": "Zain KSA", "category": "Telecom", "country": "SA"},
        {"payee_code": "BLR-SA-004", "name": "Saudi Electricity Company", "category": "Utilities", "country": "SA"},
        {"payee_code": "BLR-SA-005", "name": "National Water Company", "category": "Utilities", "country": "SA"},
        {"payee_code": "BLR-SA-006", "name": "Saudi Gas", "category": "Utilities", "country": "SA"},
    ],
    "QA": [
        {"payee_code": "BLR-QA-001", "name": "Ooredoo Qatar", "category": "Telecom", "country": "QA"},
        {"payee_code": "BLR-QA-002", "name": "Vodafone Qatar", "category": "Telecom", "country": "QA"},
        {"payee_code": "BLR-QA-003", "name": "Kahramaa (Electricity & Water)", "category": "Utilities", "country": "QA"},
    ],
    "KW": [
        {"payee_code": "BLR-KW-001", "name": "Zain Kuwait", "category": "Telecom", "country": "KW"},
        {"payee_code": "BLR-KW-002", "name": "Ooredoo Kuwait", "category": "Telecom", "country": "KW"},
        {"payee_code": "BLR-KW-003", "name": "STC Kuwait", "category": "Telecom", "country": "KW"},
        {"payee_code": "BLR-KW-004", "name": "MEW (Electricity & Water)", "category": "Utilities", "country": "KW"},
    ],
    "BH": [
        {"payee_code": "BLR-BH-001", "name": "Batelco", "category": "Telecom", "country": "BH"},
        {"payee_code": "BLR-BH-002", "name": "Zain Bahrain", "category": "Telecom", "country": "BH"},
        {"payee_code": "BLR-BH-003", "name": "STC Bahrain", "category": "Telecom", "country": "BH"},
        {"payee_code": "BLR-BH-004", "name": "EWA (Electricity & Water)", "category": "Utilities", "country": "BH"},
    ],
    "TR": [
        {"payee_code": "BLR-TR-001", "name": "Turkcell", "category": "Telecom", "country": "TR"},
        {"payee_code": "BLR-TR-002", "name": "Vodafone Turkey", "category": "Telecom", "country": "TR"},
        {"payee_code": "BLR-TR-003", "name": "Turk Telekom", "category": "Telecom", "country": "TR"},
        {"payee_code": "BLR-TR-004", "name": "BEDAS (Istanbul Electric)", "category": "Utilities", "country": "TR"},
        {"payee_code": "BLR-TR-005", "name": "IGDAS (Istanbul Gas)", "category": "Utilities", "country": "TR"},
        {"payee_code": "BLR-TR-006", "name": "ISKI (Istanbul Water)", "category": "Utilities", "country": "TR"},
        {"payee_code": "BLR-TR-007", "name": "Superonline", "category": "Internet", "country": "TR"},
    ],

    # ─── AFRICA ───
    "NG": [
        {"payee_code": "BLR-NG-001", "name": "MTN Nigeria", "category": "Telecom", "country": "NG"},
        {"payee_code": "BLR-NG-002", "name": "Airtel Nigeria", "category": "Telecom", "country": "NG"},
        {"payee_code": "BLR-NG-003", "name": "Glo Mobile", "category": "Telecom", "country": "NG"},
        {"payee_code": "BLR-NG-004", "name": "9mobile", "category": "Telecom", "country": "NG"},
        {"payee_code": "BLR-NG-005", "name": "IKEDC (Ikeja Electric)", "category": "Utilities", "country": "NG"},
        {"payee_code": "BLR-NG-006", "name": "EKEDC (Eko Electric)", "category": "Utilities", "country": "NG"},
        {"payee_code": "BLR-NG-007", "name": "AEDC (Abuja Electric)", "category": "Utilities", "country": "NG"},
        {"payee_code": "BLR-NG-008", "name": "IBEDC (Ibadan Electric)", "category": "Utilities", "country": "NG"},
        {"payee_code": "BLR-NG-009", "name": "DSTV / MultiChoice", "category": "Subscription", "country": "NG"},
        {"payee_code": "BLR-NG-010", "name": "GOtv", "category": "Subscription", "country": "NG"},
        {"payee_code": "BLR-NG-011", "name": "Spectranet", "category": "Internet", "country": "NG"},
        {"payee_code": "BLR-NG-012", "name": "Smile Communications", "category": "Internet", "country": "NG"},
    ],
    "ZA": [
        {"payee_code": "BLR-ZA-001", "name": "Vodacom South Africa", "category": "Telecom", "country": "ZA"},
        {"payee_code": "BLR-ZA-002", "name": "MTN South Africa", "category": "Telecom", "country": "ZA"},
        {"payee_code": "BLR-ZA-003", "name": "Cell C", "category": "Telecom", "country": "ZA"},
        {"payee_code": "BLR-ZA-004", "name": "Telkom SA", "category": "Telecom", "country": "ZA"},
        {"payee_code": "BLR-ZA-005", "name": "Eskom (Electricity)", "category": "Utilities", "country": "ZA"},
        {"payee_code": "BLR-ZA-006", "name": "City of Johannesburg (Services)", "category": "Utilities", "country": "ZA"},
        {"payee_code": "BLR-ZA-007", "name": "DSTV South Africa", "category": "Subscription", "country": "ZA"},
        {"payee_code": "BLR-ZA-008", "name": "Rain (Internet)", "category": "Internet", "country": "ZA"},
    ],
    "KE": [
        {"payee_code": "BLR-KE-001", "name": "Safaricom", "category": "Telecom", "country": "KE"},
        {"payee_code": "BLR-KE-002", "name": "Airtel Kenya", "category": "Telecom", "country": "KE"},
        {"payee_code": "BLR-KE-003", "name": "Telkom Kenya", "category": "Telecom", "country": "KE"},
        {"payee_code": "BLR-KE-004", "name": "Kenya Power (KPLC)", "category": "Utilities", "country": "KE"},
        {"payee_code": "BLR-KE-005", "name": "Nairobi Water", "category": "Utilities", "country": "KE"},
        {"payee_code": "BLR-KE-006", "name": "DSTV Kenya", "category": "Subscription", "country": "KE"},
        {"payee_code": "BLR-KE-007", "name": "Zuku (Internet/TV)", "category": "Internet", "country": "KE"},
    ],
    "GH": [
        {"payee_code": "BLR-GH-001", "name": "MTN Ghana", "category": "Telecom", "country": "GH"},
        {"payee_code": "BLR-GH-002", "name": "Vodafone Ghana", "category": "Telecom", "country": "GH"},
        {"payee_code": "BLR-GH-003", "name": "AirtelTigo Ghana", "category": "Telecom", "country": "GH"},
        {"payee_code": "BLR-GH-004", "name": "ECG (Electricity Company of Ghana)", "category": "Utilities", "country": "GH"},
        {"payee_code": "BLR-GH-005", "name": "Ghana Water Company", "category": "Utilities", "country": "GH"},
        {"payee_code": "BLR-GH-006", "name": "DSTV Ghana", "category": "Subscription", "country": "GH"},
    ],
    "EG": [
        {"payee_code": "BLR-EG-001", "name": "Vodafone Egypt", "category": "Telecom", "country": "EG"},
        {"payee_code": "BLR-EG-002", "name": "Orange Egypt", "category": "Telecom", "country": "EG"},
        {"payee_code": "BLR-EG-003", "name": "Etisalat Egypt (e&)", "category": "Telecom", "country": "EG"},
        {"payee_code": "BLR-EG-004", "name": "WE (Telecom Egypt)", "category": "Telecom", "country": "EG"},
        {"payee_code": "BLR-EG-005", "name": "Egypt Electricity (EEHC)", "category": "Utilities", "country": "EG"},
        {"payee_code": "BLR-EG-006", "name": "Town Gas Egypt", "category": "Utilities", "country": "EG"},
    ],
    "TZ": [
        {"payee_code": "BLR-TZ-001", "name": "Vodacom Tanzania", "category": "Telecom", "country": "TZ"},
        {"payee_code": "BLR-TZ-002", "name": "Airtel Tanzania", "category": "Telecom", "country": "TZ"},
        {"payee_code": "BLR-TZ-003", "name": "Tigo Tanzania", "category": "Telecom", "country": "TZ"},
        {"payee_code": "BLR-TZ-004", "name": "TANESCO (Electricity)", "category": "Utilities", "country": "TZ"},
        {"payee_code": "BLR-TZ-005", "name": "DAWASCO (Water)", "category": "Utilities", "country": "TZ"},
    ],

    # ─── OCEANIA ───
    "AU": [
        {"payee_code": "BLR-AU-001", "name": "Telstra", "category": "Telecom", "country": "AU"},
        {"payee_code": "BLR-AU-002", "name": "Optus", "category": "Telecom", "country": "AU"},
        {"payee_code": "BLR-AU-003", "name": "Vodafone Australia", "category": "Telecom", "country": "AU"},
        {"payee_code": "BLR-AU-004", "name": "TPG Telecom", "category": "Telecom", "country": "AU"},
        {"payee_code": "BLR-AU-005", "name": "AGL Energy", "category": "Utilities", "country": "AU"},
        {"payee_code": "BLR-AU-006", "name": "Origin Energy", "category": "Utilities", "country": "AU"},
        {"payee_code": "BLR-AU-007", "name": "EnergyAustralia", "category": "Utilities", "country": "AU"},
        {"payee_code": "BLR-AU-008", "name": "Sydney Water", "category": "Utilities", "country": "AU"},
        {"payee_code": "BLR-AU-009", "name": "NBN Co (Internet)", "category": "Internet", "country": "AU"},
        {"payee_code": "BLR-AU-010", "name": "Foxtel", "category": "Subscription", "country": "AU"},
    ],
    "NZ": [
        {"payee_code": "BLR-NZ-001", "name": "Spark New Zealand", "category": "Telecom", "country": "NZ"},
        {"payee_code": "BLR-NZ-002", "name": "Vodafone New Zealand", "category": "Telecom", "country": "NZ"},
        {"payee_code": "BLR-NZ-003", "name": "2degrees", "category": "Telecom", "country": "NZ"},
        {"payee_code": "BLR-NZ-004", "name": "Mercury Energy", "category": "Utilities", "country": "NZ"},
        {"payee_code": "BLR-NZ-005", "name": "Genesis Energy", "category": "Utilities", "country": "NZ"},
        {"payee_code": "BLR-NZ-006", "name": "Watercare", "category": "Utilities", "country": "NZ"},
        {"payee_code": "BLR-NZ-007", "name": "Contact Energy", "category": "Utilities", "country": "NZ"},
        {"payee_code": "BLR-NZ-008", "name": "Sky TV NZ", "category": "Subscription", "country": "NZ"},
    ],
}
